<?php
/**
 * Created by PhpStorm.
 * User: mgarber
 * Date: 3/18/18
 * Time: 6:12 PM
 */

namespace App\Tests\Subscriber;


use App\Subscriber\Status;
use App\Subscriber\StatusEvent;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Dotenv\Dotenv;

class CommandStatusSubscriberTest extends KernelTestCase
{
   public static function setUpBeforeClass()
   {
       parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
       // TODO: Remove next line when environment variables are set up make conditional for production
       (new Dotenv())->load( __DIR__ . '/../../.env' );
       // TODO: Change dev->prod, false for production
   }

   public function setUp()
   {
       parent::setUp(); // TODO: Change the autogenerated stub
       self::$kernel=self::bootKernel();
   }

    public function testContainerConnectsToListener()
    {
        $container=self::$kernel->getContainer();
        $dispatcher=self::$kernel->getContainer()->get('event_dispatcher');
        $event = new StatusEvent(new Status(Status::COMMENCE,100));
        $subscriber=$container->get('app.command.subscriber');
        $dispatcher->addSubscriber($subscriber);
        $dispatcher->dispatch('status.update',$event);
        $this->assertTrue(true);
    }
}