swiftmailer:
    transport: smtp
    host: smtp.gmail.com
    port: 587
    encryption: tls
    auth_mode: plain
    username: mgarber@georgiadancesport.org
    password: mag3B4#gds$2016
    spool: { type: 'memory' }
    logging: '%kernel.debug%'
    delivery_addresses: ['mgarber356@comcast.net']
