<?php

namespace App\Repository\Configuration;

use App\Entity\Configuration\Miscellaneous;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;

/**
 * MiscellaneousRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class MiscellaneousRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct( $registry,Miscellaneous::class );
    }

    public function getEntityManager()
    {
        return parent::getEntityManager();
    }

}
