<?php
/**
 * Created by PhpStorm.
 * User: mgarber
 * Date: 2/23/18
 * Time: 10:30 AM
 */

namespace App\Repository\Access;


use App\Entity\Access\Sessions;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;

class SessionsRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct( $registry, Sessions::class );
    }

    public function getEntityManager()
    {
        return parent::getEntityManager(); // TODO: Change the autogenerated stub
    }
}