<?php

namespace App\Repository\Access;

use Doctrine\ORM\EntityRepository;

/**
 * UserHasWorkareaRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserHasWorkareaRepository extends EntityRepository
{
}
