<?php

namespace App\Repository\Access;

use Doctrine\ORM\EntityRepository;

/**
 * UserHasChannelRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserHasChannelRepository extends EntityRepository
{
    public function __construct()
    {
        //TODO : Load sales repository for channel
    }
}
