<?php

namespace App\Repository\Sales;

use App\Entity\Sales\Tag;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;


/**
 * TagRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TagRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct( $registry, Tag::class);
    }

    /**
     * @param string $tagName
     * @return Tag|null|object
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function fetch(string $tagName){
        $tag=$this->findOneBy(['name'=>$tagName]);
        if(!$tag){
            $tag = new Tag();
            $tag->setName($tagName);
            $em = $this->getEntityManager();
            $em->persist($tag);
            $em->flush();
            return $tag;
        }
        return $tag;
    }

    public function getEntityManager()
    {
        return parent::getEntityManager();
    }
}